### ISSUE TITLE
Output not consistent and missing @throws annotations

### ISSUE THREAD

**Issue by ghost** [alphp/strftime#22]
The old `strftime` returned false when conversion failed. This one throws `InvalidArgumentException`.

To reproduce:
```
$formatted = \PHP81_BC\strftime('%d.%m.%Y', '30-11- -0001');
var_dump($formatted);
```

Expected: `bool(false)`
Actual: `Uncaught Exception: DateTime::__construct(): Failed to parse time string (30-11--0001) at position 0 (3): Unexpected character in ..../php81_bc/strftime/src/php8.1-strftime.php:37`

Please return the original behavior of returning `string|false`, or add a `@throws` annotation so it's immediately obvious in any semi-competent IDE that this function now throws an exception.

See return values here: https://www.php.net/manual/en/function.strftime.php

**Comment by alphp** [comment]
This implementation of the strftime function was made as an aid to backwards compatibility in view of the fact that the original function was deprecated.

However, a clone that worked exactly like the original function was not made.

As you can read in this discussion #8, it was decided to create a new implementation that would correct the problems of the original function.

For this reason, this implementation has always thrown an exception with invalid arguments instead of returning false.

However, the PHPDoc signature did not stipulate that the function could throw an InvalidArgumentException.

That bug has been fixed in https://github.com/alphp/strftime/commit/d115595bccd137660d25e9e05fb656143594b404
